### ISSUE TITLE
how to make inferences

### ISSUE THREAD

**Issue by songyh10** [ying09/TextFuseNet#18]
By running the demo, we can get a visualization image with bounding boxes and characters. However, is there any inference command which can return the words or phrases instead of only characters? Thanks! @Real-YeJ

**Comment by Real-YeJ** [comment]
@songyh10  we save the contour points of word-level text as txt file. It‘s easy to draw the contours on images by python.

**Comment by songyh10** [comment]
Then how do you compare the performance of TextFuseNet with other methods on the benchmark datasets, e.g. ICDAR2015 or Total-Text? Do you have some existing relevant inference code or tools to make this performance comparison? Thanks! @Real-YeJ

**Comment by Real-YeJ** [comment]
@songyh10  ic15: https://rrc.cvc.uab.es/?ch=4      totaltext: https://github.com/cs-chan/Total-Text-Dataset

**Comment by animesh-007** [comment]
> Then how do you compare the performance of TextFuseNet with other methods on the benchmark datasets, e.g. ICDAR2015 or Total-Text? Do you have some existing relevant inference code or tools to make this performance comparison? Thanks! @Real-YeJ

Hello @songyh10. Were you able to calculate F-measure, Recall, and Precision using this code. If so, Can you guide me on how to do the same?

**Comment by Real-YeJ** [comment]
@animesh-007 please pay attention to our update for evaluation

**Comment by StudentChen** [comment]
> > Then how do you compare the performance of TextFuseNet with other methods on the benchmark datasets, e.g. ICDAR2015 or Total-Text? Do you have some existing relevant inference code or tools to make this performance comparison? Thanks! @Real-YeJ
> 
> Hello @songyh10. Were you able to calculate F-measure, Recall, and Precision using this code. If so, Can you guide me on how to do the same?

hi,do you solve this problem? can you help me how to do the same? Thank you so much.

**Comment by animesh-007** [comment]
> > > Then how do you compare the performance of TextFuseNet with other methods on the benchmark datasets, e.g. ICDAR2015 or Total-Text? Do you have some existing relevant inference code or tools to make this performance comparison? Thanks! @Real-YeJ
> > 
> > 
> > Hello @songyh10. Were you able to calculate F-measure, Recall, and Precision using this code. If so, Can you guide me on how to do the same?
> 
> hi,do you solve this problem? can you help me how to do the same? Thank you so much.

Hi @StudentChen. You can calculate these metrics by visiting the links provided in the evaluation in the readme.
After visiting those links you can find that they have provided a script for calculating these metrics.

**Comment by StudentChen** [comment]
Thank you you you,I will have a try according to your suggestion. So kind of you.

> > > > Then how do you compare the performance of TextFuseNet with other methods on the benchmark datasets, e.g. ICDAR2015 or Total-Text? Do you have some existing relevant inference code or tools to make this performance comparison? Thanks! @Real-YeJ
> > > 
> > > 
> > > Hello @songyh10. Were you able to calculate F-measure, Recall, and Precision using this code. If so, Can you guide me on how to do the same?
> > 
> > 
> > hi,do you solve this problem? can you help me how to do the same? Thank you so much.
> 
> Hi @StudentChen. You can calculate these metrics by visiting the links provided in the evaluation in the readme.
> After visiting those links you can find that they have provided a script for calculating these metrics.

Thank you you you,I will have a try according to your suggestion. So kind of you.

**Comment by animesh-007** [comment]
No problem. Let me know if you face any other issue. I will be happy to help.😇

**Comment by StudentChen** [comment]
hi,do you train this model by yourself? it needs the train dataset like the json file. do you get the train.json? Thank you for your answer.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ying09/TextFuseNet"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月7日(星期四) 中午11:04
收件人:&nbsp;"ying09/TextFuseNet"<TextFuseNet@noreply.github.com&gt;;
抄送:&nbsp;"1571786636"<1571786636@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ying09/TextFuseNet] how to make inferences (#18)





 
No problem. Let me know if you face any other issue. I will be happy to help.😇

**Comment by animesh-007** [comment]
> hi,do you train this model by yourself? it needs the train dataset like the json file. do you get the train.json? Thank you for your answer.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ying09/TextFuseNet" <notifications@github.com&gt;; 发送时间:&nbsp;2021年1月7日(星期四) 中午11:04 收件人:&nbsp;"ying09/TextFuseNet"<TextFuseNet@noreply.github.com&gt;; 抄送:&nbsp;"1571786636"<1571786636@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;; 主题:&nbsp;Re: [ying09/TextFuseNet] how to make inferences (#18) No problem. Let me know if you face any other issue. I will be happy to help.😇 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Hi @StudentChen, yes you have to create json files in coco format.

**Comment by StudentChen** [comment]
thank you，by the way，Could you please tell me how to make it? is there direct conversion tool or code? and the dataset format must like the author's annotation example? I have learned that there are some datasets' coco format json file online,but I am not sure it is suitable for this model. if it is convenient for you to send me your train.json through e-mail individually, I just want to study this model.Thank you so much.Anyway Good luck to you, thank you sincerely.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Animesh Gupta"<notifications@github.com&gt;; 
发送时间: 2021年2月6日(星期六) 晚上11:30
收件人: "ying09/TextFuseNet"<TextFuseNet@noreply.github.com&gt;; 
抄送: "1571786636"<1571786636@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [ying09/TextFuseNet] how to make inferences (#18)





  
hi,do you train this model by yourself? it needs the train dataset like the json file. do you get the train.json? Thank you for your answer.
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ying09/TextFuseNet" <notifications@github.com&gt;; 发送时间:&nbsp;2021年1月7日(星期四) 中午11:04 收件人:&nbsp;"ying09/TextFuseNet"<TextFuseNet@noreply.github.com&gt;; 抄送:&nbsp;"1571786636"<1571786636@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;; 主题:&nbsp;Re: [ying09/TextFuseNet] how to make inferences (#18) No problem. Let me know if you face any other issue. I will be happy to help.😇 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
  
Hi @StudentChen, yes you have to create json files in coco format.

**Comment by animesh-007** [comment]
> thank you，by the way，Could you please tell me how to make it? is there direct conversion tool or code? and the dataset format must like the author's annotation example? I have learned that there are some datasets' coco format json file online,but I am not sure it is suitable for this model. if it is convenient for you to send me your train.json through e-mail individually, I just want to study this model.Thank you so much.Anyway Good luck to you, thank you sincerely.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Animesh Gupta"<notifications@github.com&gt;; 发送时间: 2021年2月6日(星期六) 晚上11:30 收件人: "ying09/TextFuseNet"<TextFuseNet@noreply.github.com&gt;; 抄送: "1571786636"<1571786636@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 主题: Re: [ying09/TextFuseNet] how to make inferences (#18) hi,do you train this model by yourself? it needs the train dataset like the json file. do you get the train.json? Thank you for your answer. … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ying09/TextFuseNet" <notifications@github.com&gt;; 发送时间:&nbsp;2021年1月7日(星期四) 中午11:04 收件人:&nbsp;"ying09/TextFuseNet"<TextFuseNet@noreply.github.com&gt;; 抄送:&nbsp;"1571786636"<1571786636@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;; 主题:&nbsp;Re: [ying09/TextFuseNet] how to make inferences (#18) No problem. Let me know if you face any other issue. I will be happy to help.😇 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. Hi @StudentChen, yes you have to create json files in coco format. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Sure. You can send one mail on animeshagarwal7@gmail.com and we can talk over the mail then.

**Comment by StudentChen** [comment]
Thank you very much.I have done it as you told me（my email:1571786636@qq.com）.Hope to get your answer as soon as possible.&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Animesh Gupta"<notifications@github.com&gt;; 
发送时间: 2021年2月6日(星期六) 晚上11:30
收件人: "ying09/TextFuseNet"<TextFuseNet@noreply.github.com&gt;; 
抄送: "1571786636"<1571786636@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [ying09/TextFuseNet] how to make inferences (#18)





  
hi,do you train this model by yourself? it needs the train dataset like the json file. do you get the train.json? Thank you for your answer.
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ying09/TextFuseNet" <notifications@github.com&gt;; 发送时间:&nbsp;2021年1月7日(星期四) 中午11:04 收件人:&nbsp;"ying09/TextFuseNet"<TextFuseNet@noreply.github.com&gt;; 抄送:&nbsp;"1571786636"<1571786636@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;; 主题:&nbsp;Re: [ying09/TextFuseNet] how to make inferences (#18) No problem. Let me know if you face any other issue. I will be happy to help.😇 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
  
Hi @StudentChen, yes you have to create json files in coco format.
